### PR TITLE
rt: minor replyPop spec changes

### PR DESCRIPTION
**Pull request by corlewis**

### CODE REVIEW

**Review by MitchellBuckley — APPROVED** [review]
Can't find anything to comment on! Looks good!

**Review by michaelmcinerney — APPROVED** [review]
Merge it!

**Review by mktnk3 — CHANGES_REQUESTED** [review]
Nice! Glad to see that the change didn’t need too much work.

**Comment by mktnk3** [comment]
Sorry, that was just a mistake.

**Review by mktnk3 — APPROVED** [review]

**Pull request merged**
