### PR TITLE
Import documentation: CRefine notes

### PR DESCRIPTION
**Pull request by corlewis**
We import some documentation with notes/issues on the refinement from
Haskell to C.

The file is a Markdown-ified version of previous documentation hosted at
UNSW.

### CODE REVIEW

**Comment by corlewis** [comment]
I'm a bit confused by the Trailing Whitespace failure. It looks like the syntax for one of the headings is exactly the wrong length and that the test thinks that it is a conflict marker.

Should I switch to the more standard heading syntax of `#`, or ignore the test failure?

**Comment by lsf37** [comment]
> I'm a bit confused by the Trailing Whitespace failure. It looks like the syntax for one of the headings is exactly the wrong length and that the test thinks that it is a conflict marker.

Nice one :-)
 
> Should I switch to the more standard heading syntax of `#`, or ignore the test failure?

Using `#` is probably better for now, because we'll otherwise get the same failure whenever we edit the file.

**Review by lsf37 — APPROVED** [review]
Happy with it as it is for now (when the checks pass). The file could do with a bit of cleanup and modernisation, but we can do that in a separate round.

**Comment by corlewis** [comment]
> Using `#` is probably better for now, because we'll otherwise get the same failure whenever we edit the file.

Ok, I've switched everything over to `#` now. For completeness, as part of this I did change the level of many of the headings in an attempt to be more consistent.

**Review by ryybrr — APPROVED** [review]

**Review by Xaphiosis — APPROVED** [review]

**Comment by Xaphiosis** [comment]
Nicely done, now it's in docs and can be seen by all, opening a path to potential updates in the future!

**Pull request merged**
