### PR TITLE
Merge `master` into `rt`

### PR DESCRIPTION
**Pull request by michaelmcinerney**

### CODE REVIEW

**Comment by michaelmcinerney** [comment]
I'm not sure how gitlint is failing if all these commit messages are from the master branch and the tests must have passed there

**Comment by lsf37** [comment]
It looks like gitlint is failing on old `rt` commits (the selection logic doesn't work properly for following merge commits since we don't usually do these). We should fix up those old commits at some point, but it's unrelated to this merge.

**Comment by lsf37** [comment]
This is looking good, I'm running a separate test board to make sure, because the PR checks don't work with merge commits. If they pass I'll push this directly to `rt`.

**Review by lsf37 — APPROVED** [review]
Local testboard has passed.

**Comment by lsf37** [comment]
Merged in 3bd85ee0175712db51c3e111dee3c5eadd968c47

**Comment by michaelmcinerney** [comment]
Thanks Gerwin. I was a bit worried about the tests but I'm glad it was all fine

**Pull request closed without merging**
