### PR TITLE
c-parser: make default SML compiler Poly/ML (not mlton)

### PR DESCRIPTION
**Pull request by mn200**
With `polyc` usable in Isabelle2019, using Poly/ML to compile the standalone tools, `mllex` and `mlyacc` is pretty straightforward.

### CODE REVIEW

**Review by lsf37 — APPROVED** [review]
This looks good from my side (and so nice to reduce dependencies).

We should run a full testboard internally to see if there are any unintended side effects. I'll start one.

**Comment by mbrcknl** [comment]
> This looks good from my side (and so nice to reduce dependencies).

I've got some issues on my Linux setup that I'm looking into. This is from `L4V_ARCH=ARM make CParser` in `tools/c-parser`:
[make.log](https://github.com/seL4/l4v/files/5122591/make.log)

> We should run a full testboard internally to see if there are any unintended side effects. I'll start one.

I've got one running at [L4V-TESTBOARD-591](https://bamboo.ts.data61.csiro.au/browse/L4V-TESTBOARD-591).

**Comment by lsf37** [comment]
> > This looks good from my side (and so nice to reduce dependencies).
> 
> I've got some issues on my Linux setup that I'm looking into. This is from `L4V_ARCH=ARM make CParser` in `tools/c-parser`:
> [make.log](https://github.com/seL4/l4v/files/5122591/make.log)

It's complaining a lot about missing `-fPIE`. Not even  sure if it means in the c-parser compile run or in poly itself. @mn200 do you have any insight there?


> > We should run a full testboard internally to see if there are any unintended side effects. I'll start one.
> 
> I've got one running at [L4V-TESTBOARD-591](https://bamboo.ts.data61.csiro.au/browse/L4V-TESTBOARD-591).

Perfect, thanks. Then I don't have to do anything ;-)

**Comment by mbrcknl** [comment]
> > I've got some issues on my Linux setup that I'm looking into. This is from `L4V_ARCH=ARM make CParser` in `tools/c-parser`:
> > [make.log](https://github.com/seL4/l4v/files/5122591/make.log)
> 
> It's complaining a lot about missing `-fPIE`. Not even sure if it means in the c-parser compile run or in poly itself. @mn200 do you have any insight there?

I'm guessing it has something to do with Poly/ML's fancy hybrid 64/32-bit mode, but I can't figure out how to override `ML_HOME` with our `.isabelle/etc/settings`.

**Comment by mbrcknl** [comment]
> I'm guessing it has something to do with Poly/ML's fancy hybrid 64/32-bit mode, but I can't figure out how to override `ML_HOME` with our `.isabelle/etc/settings`.

No, it's nothing to do with that. Even if I edit my `~/.isabelle/etc/settings` to force. `ML_PLATFORM` and `ML_HOME` to use `x86_64-linux`, I still get very similar errors, but with a different Poly/ML platform directory.

It looks more like the `libpolyml.a` in each platform of the bundled Poly/ML is incompatible with the object files produced by the corresponding call to `polyc`. Maybe `polyc` can take an `-fPIE` argument. I'll try that after dinner.

The testboard has failed, so at least it's not just me. :-)

**Comment by mn200** [comment]
On the Mac I get warning/complaints along the lines of 
```
ld: warning: could not create compact unwind for _ffi_call_unix64: does not use RBP or RSP based frame
```
but I see from the log that the `-fPIE` complaints on Linux are more fatal.  It's curious because we compile `mllex` with `polyc` in HOL4 (see, for example, logging at the top half of a [recent Travis run (line 1838)](https://travis-ci.org/github/HOL-Theorem-Prover/HOL/jobs/720872170)), both with Poly from the bleeding edge, and 5.7.1 and don't get any errors at all.

**Comment by mn200** [comment]
That's with a Travis Linux VM of some flavour or other.

**Comment by mn200** [comment]
The ultimate source of the complaints is the call to the linker (_via_ `g++`) made in the `polyc` shell-script, which is at `~/.Isabelle/contrib/polyml-5.8/<arch>/polyc`.

**Comment by lsf37** [comment]
Are we missing flags that we should be passing to `polyc`, e.g. something that was used for building the `poly` binary?

**Comment by mn200** [comment]
I'd hope the process that built `poly` generated the `polyc` at the same time.  Certainly that's what happens if you download and build `poly` as a standalone tool.

**Comment by lsf37** [comment]
> I'd hope the process that built `poly` generated the `polyc` at the same time. Certainly that's what happens if you download and build `poly` as a standalone tool.

One would hope so yes, I'm mostly fishing in the dark on this one, sorry.

**Comment by mn200** [comment]
Unfortunately, it looks pretty clear that `polyc` will not accept any c/line options to tweak linking etc; it prepopulates all of them when built.

**Comment by mn200** [comment]
I'm cut off from my Linux desktop at the moment, so I'm afraid I can't debug on Linux.

**Comment by mbrcknl** [comment]
> I'm cut off from my Linux desktop at the moment, so I'm afraid I can't debug on Linux.

I'll see if I can figure something out. But I might have to let it sit for a while. I guess that should be OK, since @mn200 has already got what he wanted out of it. :-)

**Comment by lsf37** [comment]
@mbrcknl @mn200 should we abandon this PR? It doesn't look like we're going to make progress on this.

**Comment by mbrcknl** [comment]
> @mbrcknl @mn200 should we abandon this PR? It doesn't look like we're going to make progress on this.

Yeah, seems unlikely.

**Comment by mn200** [comment]
Sure

**Comment by mbrcknl** [comment]
Abandoning for now. :-(

**Pull request closed without merging**
