### PR TITLE
asmrefine: add timeouts for debugging

### PR DESCRIPTION
**Pull request by pierzchalski**
Also cleans up some of the debug config setup and makes result reporting
more useful.

Signed-off-by: Edward Pierzchalski <ed.pierzchalski@data61.csiro.au>

### CODE REVIEW

**Review by mbrcknl — APPROVED** [review]
This looks good! Some general questions:
- Is there a seL4 pull request to go with this, with the change we discussed elsewhere, to pull the refill pointer macro out into a separate (but inlined) function?
- Regarding `init_freemem`, also discussed elsewhere, do you want to add that to the list of ignored functions?

**Comment by pierzchalski** [comment]
>     * Is there a seL4 pull request to go with this, with the change we discussed elsewhere, to pull the refill pointer macro out into a separate (but inlined) function?

Yep! It's already merged, but also not _strictly_ related to this change.

>     * Regarding `init_freemem`, also discussed elsewhere, do you want to add that to the list of ignored functions?

`init_freemem` actually finishes refining on RISCV64 MCS now, it "just" takes ~2.6 hours on my machine. It's an open question whether we want to ignore long-running but successful refinements.

**Comment by mbrcknl** [comment]
> > * Is there a seL4 pull request to go with this, with the change we discussed elsewhere, to pull the refill pointer macro out into a separate (but inlined) function?
> 
> Yep! It's already merged, but also not _strictly_ related to this change.

Nice. I see that I was even supposed to review it, but missed my chance. :-)

I'm wondering if it might actually help with some issues we have in graph-refine. We'll see...

> > * Regarding `init_freemem`, also discussed elsewhere, do you want to add that to the list of ignored functions?
> 
> `init_freemem` actually finishes refining on RISCV64 MCS now, it "just" takes ~2.6 hours on my machine. It's an open question whether we want to ignore long-running but successful refinements.

Also nice. Let's leave it as is for the moment. If it hurts too much, we can turn it off later.

**Comment by mbrcknl** [comment]
Whoops, I only just noticed this targeted the `rt` branch. Would it make sense to backport this to `master`?

**Comment by lsf37** [comment]
It looks like cherry-picking this onto a branch off master would work and wouldn't interfere with `rt` merges later. So if you need it, please go for it.

**Pull request merged**
