### PR TITLE
lib: Requalify: better document annotation

### PR DESCRIPTION
**Pull request by Xaphiosis**
Previous attempts to update the code to allow ctrl+clicking on names resulted in markup overlap errors for arch_requalify commands. This was due to a misconception that YXML strings already containing correct position information (e.g. obtained via Parse.const) would be used directly by Proof_context.read_const/read_type_name. This is not the case. Instead, position information is adjusted for the content length, and since we add a prefix for L4V_ARCH, we got annotation that did not match the document text.

After hours of digging to uncover the above issue, we get this:
* the "check_parsed_nm" in gen_requalify was not an extra check, but a hook to do document annotation; updated comments
* use Proof_Context.check_const/check_type_name with parsed position of Parse.name, and manually report resulting markup
* since the above works for arch_requalify_const, the normal requalify_const becomes a simpler instance
* the whole Parse.const/Parse.typ was a red herring and ultimately did not add anything to the code except for read_const/read_type_name interaction; removed

The resulting code is simpler; a large cautionary comment remains for future generations.

### CODE REVIEW

**Comment by Xaphiosis** [comment]
Looks like this needs more work, some issues with creative requalify in CRefine got me :(

**Review by corlewis — APPROVED** [review]
Great job working through this horrible issue and thank you for the detailed comment!

**Comment by Xaphiosis** [comment]
Updated to fix the lookup of a resolved name, because somehow it's possible to look up a short name and get a qualified name that's been hidden... which for whatever reason is fine to create aliases to, but not find to resolve to (we use this in Kernel_C for temporarily making things visible to C Parser).
Added example in Requalify_Test, theory linter is complaining about diagnostic commands there.

**Review by lsf37 — APPROVED** [review]
Cool. And impressive job finding all that out, this is about as arcane as it gets.

**Review by corlewis — APPROVED** [review]
Looks even better now with the tests passing! Once again, thank you for the thorough comments in the new test.

**Pull request merged**
