### PR TITLE
github: auto-rebase platform branches

### PR DESCRIPTION
**Pull request by lsf37**
The action will abort when no clean rebase is possible, and force-push the rebased branch when the rebase over origin/master was clean.

The push will trigger proof runs on the rebased branches.

This required L4V_PLAT etc to be merged first, i.e. everything related to #639

### CODE REVIEW

**Comment by lsf37** [comment]
For discussion at this point, I'm not sure this is ready to merge yet.

This current version has no safety-rails whatsoever: it'll just rebase and force-push if the rebase is clean. In particular, this "forgets" the old branch, which may be annoying when the proofs don't work and we want to compare what changed.

This could be alleviated by first pushing to a different branch, e.g. `$branch-rebased` and then force-pushing to `$branch` once the proofs have passed there, which would be slightly safer, but only has one bit of history.

This would require using a slightly different proof action setup on the branches (the force push from ``$branch-rebased` to `$branch`  would have to go in there, and we'd not want those main branches to re-run the proofs again, since they just ran on `$branch-rebased` with the same content.

Race conditions:
 - there could be another rebase + force push while the proofs are still running. I don't think that is a problem -- in both options (with `-rebase` and without) we the old commit still exists on GitHub and continues to run, and the new push will kick off a new run.
 - pushes to seL4 or other manifest repos a) between push to master and the rebase and b) in between push to master and force push to whichever branch does the proof run. The branch run will pick up the current `devel.xml` manifest at that time, which has a specific seL4 version, and branch heads for the other repos (HOL4, graph-refine, isabelle). For seL4, this is very likely, but not guaranteed to be the same version the manifest has in the `Freeze Code` step on `master` (there would have to be a push to that manifest in the time difference between `Freeze Code` gets there and the proof run triggers its own action, which should be less than half a minute). Slightly more likelihood of getting pushes to the master branches of one of the other repos, mostly because nobody but CI usually pushes to the manifest, but the time window is the same.

I think it's fine to ignore the race conditions for now. The branch might then not be in complete sync with the default.xml manifest the master branch will push, but it will be in sync again once the next rebase is triggered from the master branch and there is no interference from other repos. (We already have the same race conditions in the PR actions and have never observed them, but they are also not important there, because we're not aiming to be in sync with a default.xml manifest at any point).

**Comment by lsf37** [comment]
Ok, I've talked myself into at least doing the `-rebased` staging thing, which is not in the current PR. This requires a bit more machinery in the branches themselves, e.g. like in this commit 68582a8a88402eae16fea245827bc6bb7127ad25.

I think this is now ready to go.

**Comment by Xaphiosis** [comment]
This looks ok to me, and the `L4V_PLAT` looks fine as well. Are the respective branches ready for this change? i.e. do they know which `L4V_PLAT` they're supposed to use? Or do we enable the branches first, run them on the `L4V_PLAT`-unaware branches and then change the branches to become aware?

**Review by Xaphiosis — APPROVED** [review]

**Review by mbrcknl — APPROVED** [review]
Looks good.

**Comment by lsf37** [comment]
> This looks ok to me, and the `L4V_PLAT` looks fine as well. Are the respective branches ready for this change? i.e. do they know which `L4V_PLAT` they're supposed to use? Or do we enable the branches first, run them on the `L4V_PLAT`-unaware branches and then change the branches to become aware?

The branches are all ready to go, this is the final bit to start off the automation. Merging now 🤞

**Pull request merged**
