### PR TITLE
Some Isabelle guides

### PR DESCRIPTION
**Pull request by lsf37**
* Matt's short guide on compacting proofs
* Matt's guide on deduplication
* Matt's and Joel's guide on arch split
* Japheth's guide on find_consts
* Japheth's guide on find_theorems

### CODE REVIEW

**Comment by lsf37** [comment]
Now ready for review. I've updated the arch split guide a little bit, and the rest has some minor tweaks, but it should be pretty much the originals otherwise (converted into markdown).

**Comment by lsf37** [comment]
> Now ready for review.

Actually, let me add the pages for `find_consts` and `find_theorems` as well to this PR.

**Comment by lsf37** [comment]
Ok, that should be it now.

**Comment by lsf37** [comment]
Testing a new feature: @ssrg-bamboo `proof`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I've set up a proof testboard for this PR [here](https://github.com/seL4/gh-testboard/blob/seL4-guides-267-112047/manifest.xml), and results should show up as `pending` in status checks in a few minutes.

**Comment by lsf37** [comment]
Now again, with L4V_TEST_ARCH provided.. @ssrg-bamboo `proof`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I've set up a proof testboard for this PR [here](https://github.com/seL4/gh-testboard/blob/seL4-guides-267-221510/manifest.xml), and results should show up as `pending` in status checks in a few minutes.

**Review by MitchellBuckley — APPROVED** [review]

**Pull request merged**
