### PR TITLE
mcs: prove cancelBadgedSends_invs

### PR DESCRIPTION
**Pull request by corlewis**
@michaelmcinerney has been working on a similar lemma, so a review from him would be helpful. Otherwise whoever has time to look at this.

### CODE REVIEW

**Comment by michaelmcinerney** [comment]
I like it!

**Comment by lsf37** [comment]
The proof seems to time out on github. Do you have a testboard run?

**Comment by corlewis** [comment]
> 
> The proof seems to time out on github. Do you have a testboard run?

Yep, and it worked fine both there and locally for me. I don't think it's related, but one of the proofs broke after rebasing over some of the recent commits that added a new precondition for `rescheduleRequired`. I think it would have been possible to show that the precondition is preserved, but it turns out that it isn't necessary. I've just added a new commit that fixes this up, maybe that will also fix the test?

**Comment by lsf37** [comment]
Let's see what it does.

**Comment by lsf37** [comment]
Ok, it looks like Refine is passing now, you just need to actually squash the sqash commit to make gitlint happy.

**Comment by corlewis** [comment]
> 
> 
> Ok, it looks like Refine is passing now, you just need to actually squash the sqash commit to make gitlint happy.

Yep, and it's nice that we have a test for that now!

**Pull request merged**
