### PR TITLE
asmrefine: add timeouts for debugging (for master)

### PR DESCRIPTION
**Pull request by mbrcknl**
This just cherry-picks a commit from `rt` to `master`, based on https://github.com/seL4/l4v/pull/65.

### CODE REVIEW

**Comment by mbrcknl** [comment]
[L4V-TESTBOARD-599](https://bamboo.ts.data61.csiro.au/browse/L4V-TESTBOARD-599)

**Review by lsf37 — APPROVED** [review]
Happy with the cherry-pick when the testboard goes through.

**Comment by mbrcknl** [comment]
Ugh, this actually breaks `master`, because it looks like the AsmRefine session was not tested against #65 before merging into the `rt` branch. I guess the best way to handle this is to add a fixup commit on top of @pierzchalski's commit in this PR. Then for `rt`, either cherry-pick the same fixup, or merge `master` into `rt`.

**Comment by lsf37** [comment]
Yes, the `rt` tests are limited to Refine only at the moment, they don't even include CRefine yet. Good that we caught this here. Fixup commit on this PR sounds good, we can then cherry-pick over or I just do another merge from `master` into `rt`, it's probably about time anyway.

**Comment by mbrcknl** [comment]
Declining this to merge #70 instead.

**Pull request closed without merging**
