### PR TITLE
lib/riscv refine: move lemma

### PR DESCRIPTION
**Pull request by lsf37**
Minor commit, mostly to check github workflow.

### CODE REVIEW

**Comment by lsf37** [comment]
Trying to get the testboard running with github remotes. First one worked, but this one does not: https://bamboo.ts.data61.csiro.au/browse/L4V-TESTBOARD-572

Will keep investigating

**Comment by mbrcknl** [comment]
Not sure what's gone wrong, but at least this line from the failed Bamboo log doesn't look right:
```
error	07-Aug-2020 18:21:43	error: Cannot fetch l4v from ssh://git@bitbucket.ts.data61.csiro.au:7999/sel4/git@github.com:lsf37/l4v
```

**Comment by lsf37** [comment]
I think I figured it out. `repo` wants ssh URLS and treats `git@github.com:lsf37/l4v` as a relative path instead of an URL. I should be able to adjust the testboard script to substitute `ssh://git@github.com/lsf37/l4v` instead.

**Comment by lsf37** [comment]
Yup, it looks like https://bamboo.ts.data61.csiro.au/browse/L4V-TESTBOARD-572 will be succeeding.

**Pull request merged**
