### PR TITLE
more github CI for master branch

### PR DESCRIPTION
**Pull request by lsf37**
Let's see how far we can push these.

### CODE REVIEW

**Comment by lsf37** [comment]
This now contains most sessions for master, but not quite all yet. I'd like to merge this one before I try to add more, so that we can already get the benefit of these tests.

**Review by mbrcknl — APPROVED** [review]
Very nice!

**Review by corlewis — APPROVED** [review]
I haven't followed the github CI that closely, but as far as I can tell this looks good!

**Comment by lsf37** [comment]
(rebased over master)

**Pull request merged**
