### PR TITLE
Consistently use /usr/bin/env to invoke python

### PR DESCRIPTION
**Pull request by cmr**

### CODE REVIEW

**Comment by Smattr** [comment]
Looks fine to me. I'm surprised we were hardcoding the Python path previously.

**Comment by lsf37** [comment]
Rebased and applied internally. Will be pushed out when the current ongoing merge is done and has passed tests (1-2 days or so).

**Comment by Smattr** [comment]
@lsf37, did you have an update on this one? I assume the merge you were referring to is notification binding. Has it passed all the internal hurdles?

**Comment by lsf37** [comment]
It's in l4v internally already. The regression server (lemma) has died last week and we're still resolving the aep -> notification rename, so things are not pushed out yet, but this part is just sitting there ready to go.

**Comment by lsf37** [comment]
Now available in d28994d860cc6b5b9608a1b0f22e32827f98afa5. Thanks for cleaning this up.

**Pull request closed without merging**
