### PR TITLE
arm-hyp: rename addressTranslateS1CPR

### PR DESCRIPTION
**Pull request by Xaphiosis**
renamed to: addressTranslateS1

(this is a basic s//g rename)

Test with seL4/seL4#763

### CODE REVIEW

**Review by lsf37 — APPROVED** [review]
Looks good, more mentions than I would have thought.

**Comment by Xaphiosis** [comment]
This now incorporates spec+proof changes needed to drop stage 1 translation from `Arch_setMRs_fault`. It affects the existing aarch64 specs, though not proofs.

**Review by lsf37 — APPROVED** [review]
Reviewed the updates and am happy with them.

**Comment by Xaphiosis** [comment]
Rebased.

**Comment by Xaphiosis** [comment]
Once AARCH64 passes, this can be merged.

**Pull request merged**
